### ISSUE TITLE
Don't write `ca.crt` file

### ISSUE THREAD

**Issue by hossainemruz** [kmodules/objectstore-api#9]
**Problem:**
Currently we write `ca.crt` file in `/etc/osm` directory if secret has `CA_CERT_DATA`.
Ref: https://github.com/kmodules/objectstore-api/blob/2558fb903e3d0756f974ed4e5769ffcf27ffea30/osm/osm.go#L193

This operation will fail if pod run as `non-root` user.

**Solution:**
Read certificate data directly from secret instead of file.
https://github.com/kmodules/objectstore-api/blob/2558fb903e3d0756f974ed4e5769ffcf27ffea30/osm/osm.go#L82

**Comment by tamalsaha** [comment]
Fixed.
